#!/usr/bin/env python3
from pathlib import Path

p = Path(__file__).resolve().parents[1] / 'assets' / 'chart-time-slider.js'
text = p.read_text(encoding='utf-8')

replacements = [
(
"""        #liquidityLatestGrid .liq-change-stack{display:flex;flex-direction:column;gap:3px;margin-left:7px;align-self:center;font-size:9px;line-height:1.15;font-weight:700;white-space:nowrap;}\n        #liquidityLatestGrid .liq-change-item{color:#86a0b6;}\n        #liquidityLatestGrid .liq-date{margin-top:7px;color:#5f7b92;font-size:9px;line-height:1.35;}\n""",
"""        #liquidityLatestGrid .liq-change-stack{display:flex;flex-direction:row;gap:16px;align-items:center;flex-wrap:wrap;margin-top:10px;font-size:10px;line-height:1.2;font-weight:700;white-space:nowrap;}\n        #liquidityLatestGrid .liq-change-item{color:#86a0b6;}\n        #liquidityLatestGrid .liq-date{margin-top:9px;color:#66839a;font-size:9px;line-height:1.35;}\n        #liquidityLatestGrid .liq-source{margin-top:3px;color:#4f6b81;font-size:8.5px;line-height:1.35;}\n"""
),
(
"""  function setLiquidityQuote(id, payload, decimals, mode='daily') {\n    const valueEl = document.getElementById(`${id}Value`);\n    const dateEl = document.getElementById(`${id}Date`);\n    if (!payload) {\n      if (valueEl) valueEl.textContent = '—';\n      if (dateEl) dateEl.textContent = 'Latest: --';\n      return;\n    }\n\n    const rawValue = mode === 'intraday'\n      ? Number(payload?.price ?? payload?.value)\n      : Number(payload?.value ?? payload?.__value);\n    if (valueEl) valueEl.textContent = Number.isFinite(rawValue) ? rawValue.toFixed(decimals) : '—';\n\n    if (!dateEl) return;\n    if (mode === 'intraday') {\n      const stamp = formatBeijingTimestamp(payload?.timestamp || payload?.live_quote_timestamp);\n      const source = payload?.source || payload?.live_quote_source || 'Yahoo Finance';\n      const status = payload?.quote_status || payload?.live_quote_status || '';\n      dateEl.textContent = `Intraday | ${stamp || '--'} | ${source}${status ? ' | '+status : ''}`;\n    } else {\n      const obs = payload?.observation_date || payload?.date || '—';\n      dateEl.textContent = `Latest official | ${obs}`;\n    }\n  }\n""",
"""  function compactLiquiditySource(source, mode='daily') {\n    const s = String(source || '').trim();\n    if (/investing/i.test(s)) return 'Investing.com';\n    if (/yahoo/i.test(s)) return 'Yahoo Finance';\n    if (/federal reserve|fred|h\\.15/i.test(s)) return 'Federal Reserve / FRED';\n    if (s) return s.replace(/\\s+(US\\s+)?(10Y|30Y).*$/i,'').trim() || s;\n    return mode === 'intraday' ? 'Market data feed' : 'Federal Reserve / FRED';\n  }\n\n  function ensureLiquiditySourceLine(id) {\n    let el = document.getElementById(`${id}Source`);\n    if (el) return el;\n    const dateEl = document.getElementById(`${id}Date`);\n    const quote = dateEl?.closest('.liq-quote');\n    if (!quote) return null;\n    el = document.createElement('div');\n    el.id = `${id}Source`;\n    el.className = 'liq-source';\n    dateEl.after(el);\n    return el;\n  }\n\n  function setLiquidityQuote(id, payload, decimals, mode='daily') {\n    const valueEl = document.getElementById(`${id}Value`);\n    const dateEl = document.getElementById(`${id}Date`);\n    const treasury = id === 'liq10y' || id === 'liq30y';\n    const sourceEl = treasury ? ensureLiquiditySourceLine(id) : null;\n    if (!payload) {\n      if (valueEl) valueEl.textContent = '—';\n      if (dateEl) dateEl.textContent = treasury ? 'Latest available · —' : 'Latest: --';\n      if (sourceEl) sourceEl.textContent = 'Source · —';\n      return;\n    }\n\n    const rawValue = mode === 'intraday'\n      ? Number(payload?.price ?? payload?.value)\n      : Number(payload?.value ?? payload?.__value);\n    if (valueEl) valueEl.textContent = Number.isFinite(rawValue) ? rawValue.toFixed(decimals) : '—';\n\n    if (!dateEl) return;\n    if (mode === 'intraday') {\n      const stamp = formatBeijingTimestamp(payload?.timestamp || payload?.live_quote_timestamp);\n      const source = payload?.source || payload?.live_quote_source || 'Yahoo Finance';\n      if (treasury) {\n        dateEl.textContent = `Latest available · ${stamp || '—'}`;\n        if (sourceEl) sourceEl.textContent = `Source · ${compactLiquiditySource(source, mode)}`;\n      } else {\n        const status = payload?.quote_status || payload?.live_quote_status || '';\n        dateEl.textContent = `Intraday | ${stamp || '--'} | ${source}${status ? ' | '+status : ''}`;\n      }\n    } else {\n      const obs = payload?.observation_date || payload?.date || '—';\n      if (treasury) {\n        dateEl.textContent = `Latest available · ${obs}`;\n        const source = payload?.source || payload?.live_quote_source || 'Federal Reserve / FRED';\n        if (sourceEl) sourceEl.textContent = `Source · ${compactLiquiditySource(source, mode)}`;\n      } else {\n        dateEl.textContent = `Latest official | ${obs}`;\n      }\n    }\n  }\n"""
),
(
"""  function ensureTreasuryChangeStack(id) {\n    let el = document.getElementById(`${id}Change`);\n    if (el) return el;\n    const valueEl = document.getElementById(`${id}Value`);\n    const row = valueEl?.closest('.liq-value-row');\n    if (!row) return null;\n    el = document.createElement('span');\n    el.id = `${id}Change`;\n    el.className = 'liq-change-stack';\n    el.innerHTML = '<span class=\"liq-change-item\">1D —</span><span class=\"liq-change-item\">1M —</span>';\n    row.appendChild(el);\n    return el;\n  }\n""",
"""  function ensureTreasuryChangeStack(id) {\n    let el = document.getElementById(`${id}Change`);\n    const valueEl = document.getElementById(`${id}Value`);\n    const row = valueEl?.closest('.liq-value-row');\n    const quote = valueEl?.closest('.liq-quote');\n    const dateEl = document.getElementById(`${id}Date`);\n    if (!row || !quote) return null;\n    if (!el) {\n      el = document.createElement('div');\n      el.id = `${id}Change`;\n      el.className = 'liq-change-stack';\n      el.innerHTML = '<span class=\"liq-change-item\">1D —</span><span class=\"liq-change-item\">1M —</span>';\n    }\n    if (dateEl) quote.insertBefore(el, dateEl);\n    else row.after(el);\n    return el;\n  }\n"""
)
]

for old, new in replacements:
    if old not in text:
        raise SystemExit('Patch anchor not found:\n' + old[:180])
    text = text.replace(old, new, 1)

p.write_text(text, encoding='utf-8')
print('Treasury cards patched: changes below value, compact latest/source lines')
